version: '3.0'

services:
  consul:
    image: securebrowsing/shield-configuration:test
    labels: [app=consul]
    ports:
      - "8500:8500"
    networks:
      - shield
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
      - CONSUL_BIND_INTERFACE=eth2
      - CONSUL=consul
      - CONSUL_CHECK_LEADER=true
    # Actual for compose running
    # hostname: consul
    # command: "agent -server -bootstrap-expect 1 -ui -client=0.0.0.0 -retry-interval 5s --log-level warn -disable-host-node-id"
    # environment:
    #   - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    #   - CONSUL_BIND_INTERFACE=eth0
    deploy:
      #replicas: 3
#      placement:
#          constraints: [node.role == manager]
      resources:
          reservations:
              memory: 128M
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      update_config:
          parallelism: 1
          delay: 10s
          failure_action: continue

  shield-admin:
    image: securebrowsing/shield-admin:latest
    ports:
        - 8181:8181
    environment:
        - SHIELD_VER=8.0.0.57
    volumes:
       - admin:/data/consul
    networks:
        - shield
  icap-server:
    image: securebrowsing/icap-server:latest
    hostname: icap-server
    environment:
        - NODE_ENV=production
        - SHIELD_VER=8.0.0.57
        - MAX_ELASTIC_CHECK_ATTEMPTS=40
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - shield
  broker-server:
<<<<<<< HEAD:Dev-Feb16/deploy-shield.yml
    image: securebrowsing/broker-server:170524-17.09-128
=======
    image: securebrowsing/broker-server:latest
>>>>>>> master:Dev-Feb16/deploy-shield-new-consul.yml
    hostname: broker-server
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - NODE_ENV=production
    networks:
      - shield
  shield-browser:
    image: securebrowsing/shield-cef:test
    environment:
         - FPS=25
         #- DEBUG_REMOTE_SITE=true
         - DISPOSE_BROWSER=true
         #- RUN_WITH_DEBUGGER=false
    networks:
        - shield
  # ports:
  #    - "3656:3656"
  #  volumes:
  #    - /home/lev/projects/SB/Containers/Docker/shield-cef/src:/app/src
    deploy:
      update_config:
        parallelism: 2
      replicas: 0
      resources:
        memory: 2GB
        memory-swap: 0
        cpu-quota: 100000
        memory-swappiness: 0
        shm-size: 1GB
  elk:
    image: securebrowsing/shield-elk:170126-09.14
    hostname: elk
    ports:
      - 5601:5601
      - 5044:5044
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s -XGET 'http://localhost:9200/_cluster/health' | grep -q yellow"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - shield
  proxy-server:
    image: securebrowsing/proxy-server:latest
    ports:
      - "3128:3128"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - shield      
  portainer:
    image: portainer/portainer:latest
    hostname: portainer
    ports:
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer:/data
    networks: 
      - shield
    deploy:
      placement:
        constraints:
          - node.role==manager
  dockerbeat:
    image: ingensi/dockbeat
    hostname: dockerbeat
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - shield
volumes:
  admin:
  portainer:

networks:
  shield:
<<<<<<< HEAD:Dev-Feb16/deploy-shield.yml
    driver: overlay
=======
    driver: bridge
>>>>>>> master:Dev-Feb16/deploy-shield-new-consul.yml
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24