version: '3.2'

services:
  shield-admin:
    image: securebrowsing/shield-admin:shieldadmin
    ports:
        - 8181:8181
    environment:
        - SHIELD_VER=shieldver
    volumes:
        - /usr/local/ericomshield/config:/data/consul
    networks:
        - shield
  icap-server:
    image: securebrowsing/icap-server:icapserver
    hostname: icap-server
    environment:
        - NODE_ENV=production
        - SHIELD_VER=shieldver
        - MAX_ELASTIC_CHECK_ATTEMPTS=40
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - shield
  shield-browser:
    image: securebrowsing/shield-cef:shieldcef
    environment:
         - FPS=25
         #- DEBUG_REMOTE_SITE=true
         - DISPOSE_BROWSER=true
         #- RUN_WITH_DEBUGGER=false
    networks:
        - shield
  # ports:
  #    - "3656:3656"
  #  volumes:
  #    - /home/lev/projects/SB/Containers/Docker/shield-cef/src:/app/src
    deploy:
      update_config:
        parallelism: 2
      replicas: 4
      resources:
        memory: 2GB
        memory-swap: 0
        cpu-quota: 100000
        memory-swappiness: 0
        shm-size: 1GB
  elk:
    image: securebrowsing/shield-elk:shieldelk
    hostname: elk
    ports:
      - 5601:5601
      - 5044:5044
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s -XGET 'http://localhost:9200/_cluster/health' | grep -q yellow"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - shield
  proxy-server:
    image: securebrowsing/proxy-server:proxyserver
    ports:
      - "3128:3128"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - shield      
  portainer:
    image: portainer/portainer:latest
    hostname: portainer
    ports:
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/portainer/data:/data
    networks: 
      - shield
    deploy:
      placement:
        constraints:
          - node.role==manager

networks:
  shield:
    external:
      name: shield-network
