version: '2.1'

services:
    consul:
        image: securebrowsing/shield-configuration:latest
        restart: always
    shield-admin:
        image: securebrowsing/shield-admin:170226-08.46
        ports:
            - 8181:8181
        restart: always
        depends_on:
          elk:
            condition: service_healthy
          consul:
            condition: service_started  
    shield-admin1:
        image: securebrowsing/shield-admin-orig:170219-20.17
        ports:
            - 8500:8500
        restart: always
        depends_on:
          elk:
            condition: service_healthy
          consul:
            condition: service_started      
    shield-browser:
        image: securebrowsing/shield-cef:170226-17.55
        restart: always
        hostname: browser
        depends_on:
          elk:
            condition: service_healthy
          consul:
            condition: service_started
        dns: 
            - 126.0.0.3
            - 8.8.8.8
    proxy-server:
        image: securebrowsing/proxy-server:170219-16.06
        hostname: proxy
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "3128:3128"
        ulimits:
          nofile:
            soft: 65535
            hard: 65535
        depends_on:
          elk:
            condition: service_healthy
          icap-server:
            condition: service_started 
          consul:
            condition: service_started
    icap-server:
        image: securebrowsing/icap-server:170224-11.05
        hostname: icap-server
        restart: always
        ports:
            - "13441:13441"
        environment:
            - NODE_ENV=production
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ulimits:
          nofile:
            soft: 65535
            hard: 65535
        depends_on:
          elk:
             condition: service_healthy
          consul:
             condition: service_started
    elk:
        image: securebrowsing/shield-elk:170126-09.14
        hostname: elk
        ports:
            - 5601:5601
            - 5044:5044
            - 9200:9200
        healthcheck:
            test: ["CMD-SHELL", "curl -s -XGET 'http://localhost:9200/_cluster/health' | grep -q yellow"]
            interval: 20s
            timeout: 10s
            retries: 5
        depends_on:
            - portainer
            - consul
    portainer:
        image: portainer/portainer
        hostname: portainer
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock            