version: '2.1'

services:
    consul:
        image: securebrowsing/shield-configuration:170327-23.06
        restart: always
    shield-admin:
        image: securebrowsing/shield-admin:170414-02.37
        ports:
            - 8181:8181
        restart: always
        environment:
            - SHIELD_VER=8.0.0.57-DEV
        volumes:
            - /usr/local/ericomshield/config:/data/consul
        depends_on:
          elk:
            condition: service_healthy
          consul:
            condition: service_started
        volumes:
            - /usr/local/ericomshield/config:/data/consul
    shield-admin1:
        image: securebrowsing/shield-admin-orig:170219-20.17
        ports:
            - 8500:8500
        restart: always
        depends_on:
          elk:
            condition: service_healthy
          consul:
            condition: service_started      
    shield-browser:
        image: securebrowsing/shield-cef:170414-16.57
        cpu_quota: 100000
        shm_size: 1GB
        mem_limit: 1GB
        memswap_limit: 0
        mem_swappiness: 0
        restart: always
        environment:
            - FPS=25
            - DEBUG_REMOTE_SITE=false
        depends_on:
          elk:
            condition: service_healthy
          consul:
            condition: service_started
    proxy-server:
        image: securebrowsing/proxy-server:170414-02.38
        hostname: proxy
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "3128:3128"
        ulimits:
          nofile:
            soft: 65535
            hard: 65535
        depends_on:
          elk:
            condition: service_healthy
          icap-server:
            condition: service_started 
          consul:
            condition: service_started
    extproxy:
        image: securebrowsing/extproxy
        hostname: extproxy
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "3138:3138"
        ulimits:
          nofile:
            soft: 65535
            hard: 65535
        depends_on:
          elk:
            condition: service_healthy
          consul:
            condition: service_started
    icap-server:
        image: securebrowsing/icap-server:170414-16.56
        hostname: icap-server
        restart: always
        environment:
            - NODE_ENV=production
            - SHIELD_VER=8.0.0.57-DEV
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        dns: 
            - 8.8.8.8
        ulimits:
          nofile:
            soft: 65535
            hard: 65535
        depends_on:
          elk:
             condition: service_healthy
          consul:
             condition: service_started
    elk:
        image: securebrowsing/shield-elk:170126-09.14
        hostname: elk
        ports:
            - 5601:5601
            - 5044:5044
            - 9200:9200
        healthcheck:
            test: ["CMD-SHELL", "curl -s -XGET 'http://localhost:9200/_cluster/health' | grep -q yellow"]
            interval: 20s
            timeout: 10s
            retries: 5
        depends_on:
            - portainer
            - consul
    portainer:
        image: portainer/portainer
        hostname: portainer
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/portainer/data:/data         
