version: '2'

services:
    nomad-server:
        image:  securebrowsing/nomad-server:latest
        restart: always
        hostname: nomad-server
        expose:
            - 4646
            - 4647
            - 4648
        ports:
            - 4646:4646
    nomad-client:
        image:  securebrowsing/nomad-client:latest
        restart: always
        expose:
            - 4646
            - 4647
            - 4648
        volumes:
            - /tmp:/tmp
    
    consul:
        image: securebrowsing/shield-configuration:latest
        restart: always
        expose:
            - 8500
    shield-admin:
        image: securebrowsing/shield-admin:latest
        ports:
            - 8500:8500
        restart: always
    shield-browser:
        image: securebrowsing/shield-browser:latest
        restart: always
        hostname: browser
        shm_size: 1GB
        ports:
            - "9090:9090"
    shield-proxy:
        image: securebrowsing/squid-proxy:latest
        hostname: proxy
        restart: always
        ports:
            - "3128:3128"
    icap-server:
        image: securebrowsing/shield-icap:latest
        hostname: icap-server
        restart: always
    shield-broker:
        image: securebrowsing/shield-broker:latest
        hostname: broker
        restart: always
    elk:
        image: alpin3/elk
        hostname: elk
        ports:
            - "5601:5601"
            - "5044:5044"
    portainer:
        image: portainer/portainer
        hostname: portainer
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock