version: '2'

services:
    nomad-server:
        image:  securebrowsing/nomad-server
        restart: always
        expose:
            - 4646
            - 4647
            - 4648
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    nui:
        image: iverberk/nomad-ui:v0.3.1
        ports:
            - 3000:3000
    consul:
        image: smebberson/alpine-consul
        restart: always
    consului:
        image: smebberson/alpine-consul-ui
        ports:
            - 8500:8500
        restart: always
    shield-browser: 
        image: securebrowsing/shield-browser:latest
        restart: always
        hostname: browser
        volumes:
            - /dev/shm:/dev/shm 
    shield-proxy:
        image: securebrowsing/shield-proxy
        hostname: proxy
        restart: always
        ports:
            - "8213:8213"
    shield-broker:
        image: securebrowsing/shield-broker
        hostname: broker
        restart: always
        volumes:
            - /dev/shm:/dev/shm 
    elk:
        image: sebp/elk
        hostname: elk
        ports:
            - "5601:5601"
            - "5044:5044"